---
name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
      - release

  pull_request:

jobs:
  verify:
    runs-on: ubuntu-18.04
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - id: cache
        name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
      - run: touch node_modules
        if: steps.cache.outputs.cache-hit == 'true'

      - name: Install dependencies
        run: make install
      - name: Compile project
        run: make recompile

      - run: make lint
      - run: make test
